language: python

python:
  - "2.7"

install:
  - pip install .
  - pip install -r requirements.txt

script: sms "TravisCI"

notifications:
  slack:
    secure: "bLeOdIi9cRt8YLnq774ib73bSXZ1NDJ+mTi2khyzsaj6tr+Ld6u85J/FRyEvMEYryiRvp1LPp1naeFvq96r1f3x3FZVnhJ7+DxBSdIHf+s3F7AOeFIohNKaYGrH2YLCWhbIk/ypMTR9iCVl8B0cE//Jf6UV7w3LC9veyMaB+sFOCxOtCqHRYSUpcb8EupRKfhguLPM06/nxBiiK6BZBvD/jLXIxzjDS33sRouGCGlx6Nv005YbJPvtP/Chk7c1XAlz3kngSBGA7QM88YtU0wR0qp1awrBSixF53lgCre2ThKvZe0pClSn+/us4y1ahtLRam5iS9wGN6Nb8pgBxr5L/46lv0xl067OjK0e7XE0NZy3ATrWpy7xas7/i45JdlNe286WrBDzqdjdtuoHWmzOVsWwiTGkP7gcwrVlPiQiPKvSFYo2/TxwmiTNMtKjP0nO5jbAyfLnEv/1wA6TYsnhwekrH01e5ZJ/YLwAqd9Pv3Klbmr+/21EtBjQsnIJyUdB+6jeED1g2Agml0pEFPdgk3ElZjglWMP0u++Kw9zalSs669BWUZ+DJQAHPIlx+pUl5a833t8dC32HL6lsFJaUvHx29mhOkuGXqYUYroIcekuveGBKRkY5ErjDHxrn77y5P4NdpnGy5pr9fmCGLEFGSTs5N+a+/AciGRYO0jk+4M="
